//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CraftHub.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentTheme {
            get {
                return ((string)(this["CurrentTheme"]));
            }
            set {
                this["CurrentTheme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentLanguage {
            get {
                return ((string)(this["CurrentLanguage"]));
            }
            set {
                this["CurrentLanguage"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectRootFolder {
            get {
                return ((string)(this["ProjectRootFolder"]));
            }
            set {
                this["ProjectRootFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFolders"]));
            }
            set {
                this["RecentFolders"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileExplorerVisible {
            get {
                return ((bool)(this["FileExplorerVisible"]));
            }
            set {
                this["FileExplorerVisible"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double FileExplorerWidth {
            get {
                return ((double)(this["FileExplorerWidth"]));
            }
            set {
                this["FileExplorerWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileExplorerJsonOnly {
            get {
                return ((bool)(this["FileExplorerJsonOnly"]));
            }
            set {
                this["FileExplorerJsonOnly"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDiffOnSave {
            get {
                return ((bool)(this["ShowDiffOnSave"]));
            }
            set {
                this["ShowDiffOnSave"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotificationPopups {
            get {
                return ((bool)(this["ShowNotificationPopups"]));
            }
            set {
                this["ShowNotificationPopups"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JsonChangesWindowWidth {
            get {
                return ((double)(this["JsonChangesWindowWidth"]));
            }
            set {
                this["JsonChangesWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JsonChangesWindowHeight {
            get {
                return ((double)(this["JsonChangesWindowHeight"]));
            }
            set {
                this["JsonChangesWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JsonChangesWindowX {
            get {
                return ((int)(this["JsonChangesWindowX"]));
            }
            set {
                this["JsonChangesWindowX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JsonChangesWindowY {
            get {
                return ((int)(this["JsonChangesWindowY"]));
            }
            set {
                this["JsonChangesWindowY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JsonChangesWindowMaximized {
            get {
                return ((bool)(this["JsonChangesWindowMaximized"]));
            }
            set {
                this["JsonChangesWindowMaximized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JsonCompareWindowWidth {
            get {
                return ((double)(this["JsonCompareWindowWidth"]));
            }
            set {
                this["JsonCompareWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JsonCompareWindowHeight {
            get {
                return ((double)(this["JsonCompareWindowHeight"]));
            }
            set {
                this["JsonCompareWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JsonCompareWindowX {
            get {
                return ((int)(this["JsonCompareWindowX"]));
            }
            set {
                this["JsonCompareWindowX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JsonCompareWindowY {
            get {
                return ((int)(this["JsonCompareWindowY"]));
            }
            set {
                this["JsonCompareWindowY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JsonCompareWindowMaximized {
            get {
                return ((bool)(this["JsonCompareWindowMaximized"]));
            }
            set {
                this["JsonCompareWindowMaximized"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompareIgnoreKeyOrder {
            get {
                return ((bool)(this["CompareIgnoreKeyOrder"]));
            }
            set {
                this["CompareIgnoreKeyOrder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompareIgnoreArrayOrder {
            get {
                return ((bool)(this["CompareIgnoreArrayOrder"]));
            }
            set {
                this["CompareIgnoreArrayOrder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompareCaseInsensitive {
            get {
                return ((bool)(this["CompareCaseInsensitive"]));
            }
            set {
                this["CompareCaseInsensitive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompareIgnoreNullAndEmpty {
            get {
                return ((bool)(this["CompareIgnoreNullAndEmpty"]));
            }
            set {
                this["CompareIgnoreNullAndEmpty"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CompareIgnoredPaths {
            get {
                return ((string)(this["CompareIgnoredPaths"]));
            }
            set {
                this["CompareIgnoredPaths"] = value;
            }
        }
    }
}
